version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle_cache:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_cache:
  yarn_cache: